# file: .github/workflows/hello_world.yml
name: hello-world
# on – определяет события, которые запускают воркфлоу
on: push
# задания которое воркфлщн дольжно выполнить
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    # список шагов, которые надо выполнить
    steps:
      - uses: actions/checkout@v4
        # run – произвольная bash-команда
        # make say-hello команда в Makefile которая выведет на экран "Hello, World!"
      - name: Run command
        run: |
          make say-hello
